account:
  uin: 3519974008 # QQ账号
  password: ''
  encrypt: false
  status: 0
  relogin:
    delay: 3
    interval: 3
    max-times: 0

  use-sso-address: true
  allow-temp-session: false

heartbeat:
  interval: 5

message:
  post-format: string
  ignore-invalid-cqcode: false
  force-fragment: false
  fix-url: false
  proxy-rewrite: ''
  report-self-message: false
  remove-reply-at: false
  extra-reply-data: false
  skip-mime-scan: false

output:
  log-level: warn
  log-aging: 15
  log-force-new: true
  log-colorful: true
  debug: false

default-middlewares: &default
  access-token: ''
  filter: ''
  rate-limit:
    enabled: false
    frequency: 1
    bucket: 1

database:
  leveldb:
    enable: true

  cache:
    image: data/image.db
    video: data/video.db

servers:
  - http:
      host: cq
      port: 5700
      timeout: 30
      middlewares:
        <<: *default
      post:
        - url: http://bot:8080
          secret: ''
